#!/usr/bin/env python3
"""Render a clean local HTML dashboard from a TasteGraph JSON (no effect soup)."""

from __future__ import annotations

import argparse
import html
import json
import sys
from pathlib import Path


def esc(s: str) -> str:
    return html.escape(s or "", quote=True)


def cards(nodes, kind: str) -> str:
    out = []
    for n in nodes or []:
        label = esc(n.get("label") or n.get("id"))
        desc = esc(n.get("description") or "")
        conf = esc(str(n.get("confidence") or ""))
        cat = esc(str(n.get("category") or ""))
        border = "#c45c4a" if kind == "anti" else "#c9a24a"
        out.append(
            f'<div class="card" style="border-left:3px solid {border}">'
            f'<div class="tag">{cat or kind} · {conf}</div>'
            f"<b>{label}</b><p>{desc}</p></div>"
        )
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("path")
    ap.add_argument("--out", required=True)
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    data = json.loads(Path(args.path).read_text(encoding="utf-8"))
    m = data.get("metadata") or {}
    title = esc(m.get("title") or "TasteGraph")
    version = esc(str(m.get("graph_version") or ""))
    north = esc(data.get("north_star") or "")
    tags = " ".join(f'<span class="pill">{esc(t)}</span>' for t in (data.get("quick_tags") or []))

    motion = ""
    for s in data.get("motion_stack") or []:
        motion += (
            f'<div class="step"><b>{esc(str(s.get("order")))}. {esc(s.get("label"))}</b>'
            f'<span>{esc(s.get("description"))}</span></div>'
        )

    doc = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>{title} {version}</title>
<style>
  :root {{
    --bg:#0b0c0f; --panel:#12141a; --ink:#ece8e1; --muted:#9a948a;
    --line:#2a2d36; --gold:#c9a24a; --soft:#1a1d26;
  }}
  * {{ box-sizing:border-box; margin:0; padding:0; }}
  body {{
    font-family: ui-sans-serif, system-ui, sans-serif;
    background:var(--bg); color:var(--ink);
    line-height:1.45; padding:40px 24px 64px;
  }}
  .wrap {{ max-width:1080px; margin:0 auto; }}
  .kicker {{ color:var(--gold); letter-spacing:.16em; text-transform:uppercase;
    font-size:12px; font-weight:700; margin-bottom:8px; }}
  h1 {{ font-size:36px; font-weight:650; letter-spacing:-.02em; margin-bottom:12px; }}
  .north {{ color:var(--muted); font-size:17px; max-width:70ch; margin-bottom:28px; }}
  .north strong {{ color:var(--gold); font-weight:600; }}
  h2 {{ font-size:16px; margin:28px 0 12px; letter-spacing:.04em; text-transform:uppercase; color:var(--muted); }}
  .grid {{ display:grid; grid-template-columns:repeat(auto-fill,minmax(240px,1fr)); gap:12px; }}
  .card {{ background:var(--panel); border:1px solid var(--line); border-radius:12px; padding:14px; }}
  .card .tag {{ font-size:11px; color:var(--gold); letter-spacing:.08em; text-transform:uppercase; margin-bottom:6px; }}
  .card b {{ display:block; margin-bottom:6px; }}
  .card p {{ color:var(--muted); font-size:13px; }}
  .step {{ background:var(--soft); border:1px solid var(--line); border-radius:10px;
    padding:12px; margin-bottom:8px; display:flex; flex-direction:column; gap:4px; }}
  .step span {{ color:var(--muted); font-size:13px; }}
  .pill {{ display:inline-block; border:1px solid var(--line); border-radius:999px;
    padding:6px 10px; margin:0 6px 6px 0; font-size:12px; color:var(--ink); }}
  footer {{ margin-top:36px; color:var(--muted); font-size:12px; border-top:1px solid var(--line); padding-top:16px; }}
</style>
</head>
<body>
  <div class="wrap">
    <div class="kicker">TasteGraph · local dashboard</div>
    <h1>{title} <span style="color:var(--muted);font-weight:500">{version}</span></h1>
    <p class="north"><strong>North star:</strong> {north}</p>

    <h2>Hard loves</h2>
    <div class="grid">{cards(data.get("hard_loves"), "love")}</div>

    <h2>Hard antis</h2>
    <div class="grid">{cards(data.get("hard_antis"), "anti")}</div>

    <h2>Motion stack</h2>
    {motion or "<p style='color:var(--muted)'>(none)</p>"}

    <h2>Quick tags</h2>
    <div>{tags or "<span class='pill'>(none)</span>"}</div>

    <footer>Privacy-first · no network required · generated by tastegraph skill</footer>
  </div>
</body>
</html>
"""
    if args.dry_run:
        print(doc[:400])
        return 0
    Path(args.out).write_text(doc, encoding="utf-8", newline="\n")
    print(f"Wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
